name: santa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-131.0.dev <4.0.0'

dependencies:
  crypto: ^3.0.3
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14

dev_dependencies:
  grizzly_io: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  html: ^0.15.4

flutter:
  uses-material-design: true
