name: santa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  crypto: ^3.0.3
  firebase_core: ^4.2.1
  firebase_database: ^12.0.4
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14

dev_dependencies:
  grizzly_io: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  html: ^0.15.4

flutter:
  uses-material-design: true
